# Generated by Django 4.1.1 on 2022-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_module_delete_basemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
