# Generated by Django 4.1.1 on 2022-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_module_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parent_module',
            field=models.CharField(default='', max_length=255),
        ),
    ]
