# Generated by Django 4.1.1 on 2022-09-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_module_parent_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
    ]
