# Generated by Django 4.1.1 on 2022-09-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='status',
            new_name='is_active',
        ),
    ]
