# Generated by Django 4.1.1 on 2022-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_status_university_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.IntegerField()),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('hindi_name', models.TextField()),
                ('description', models.TextField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
