# Generated by Django 4.1.1 on 2022-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_bloodgroup_boardsconfiguration_classtype_roommaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('prefix', models.CharField(max_length=250)),
                ('suffix', models.CharField(max_length=250)),
                ('numeric_value', models.IntegerField()),
                ('numeric_length', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('prefix', models.CharField(max_length=250)),
                ('suffix', models.CharField(max_length=250)),
                ('numeric_value', models.IntegerField()),
                ('numeric_length', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
